from __future__ import annotations

INTENT_CHASE = 0
INTENT_ENGAGE = 1
INTENT_EVADE = 2
INTENT_REPOSITION = 3

INTENT_LABELS = {
    INTENT_CHASE: "CHASE",
    INTENT_ENGAGE: "ENGAGE",
    INTENT_EVADE: "EVADE",
    INTENT_REPOSITION: "REPOSITION",
}

RL_ACTION_LABELS = INTENT_LABELS
RL_DISTANCE_LABELS = {0: "close", 1: "mid", 2: "far"}
RL_DIRECTION_LABELS = {0: "front", 1: "left", 2: "right", 3: "back"}
RL_HP_LABELS = {0: "low", 1: "mid", 2: "high"}
PACK_DISTANCE_LABELS = {0: "near", 1: "mid", 2: "far", 3: "very_far/none"}

TARGET_LOCK_MIN_SECONDS = 0.6
TARGET_SWITCH_HYSTERESIS = 0.8

MAIN_STATE_PLAYING = "playing"
MAIN_STATE_GAME_OVER = "game_over"

APP_STATE_MENU = "menu"
APP_STATE_PLAY_MAIN = "play_main"
APP_STATE_PLAY_TRAINING = "play_training"
APP_STATE_PAUSED = "paused"
APP_STATE_GAME_OVER = "game_over"

SCRIPT_STATE_PATROL = "PATROL"
SCRIPT_STATE_CHASE = "CHASE"
SCRIPT_STATE_ENGAGE = "ENGAGE"
SCRIPT_STATE_SEARCH = "SEARCH"
SCRIPT_STATE_RETURN = "RETURN"

SCRIPT_STATE_COLORS = {
    SCRIPT_STATE_PATROL: (156, 196, 236),
    SCRIPT_STATE_CHASE: (255, 180, 96),
    SCRIPT_STATE_ENGAGE: (255, 96, 96),
    SCRIPT_STATE_SEARCH: (255, 220, 96),
    SCRIPT_STATE_RETURN: (160, 236, 160),
}
